CREATE TABLE [dbo].[OFTA_SuratDinas]
(
	SuratDinasID VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_SuratDinas_SuratDinasID DEFAULT(''),
	TglJamCreate DATETIME NOT NULL CONSTRAINT DF_OFTA_SuratDinas_TglJamCreate DEFAULT('1900-01-01T00:00:00'),

	PegID VARCHAR(5) NOT NULL CONSTRAINT DF_OFTA_SuratDinas_PegID DEFAULT(''),
	NoSurat VARCHAR(30) NOT NULL CONSTRAINT DF_OFTA_SuratDinas_NoSurat DEFAULT(''),
	NoKontrak VARCHAR(30) NOT NULL CONSTRAINT DF_OFTA_SuratDinas_NoKontrak DEFAULT(''),

	TglMulai DATETIME NOT NULL CONSTRAINT DF_OFTA_SuratDinas_TglMulasi DEFAULT('1900-01-01T00:00:00'),
	TglSelesai DATETIME NOT NULL CONSTRAINT DF_OFTA_SuratDinas_TglSelesai DEFAULT('1900-01-01T00:00:00'),
	Keperluan VARCHAR(256) NOT NULL CONSTRAINT DF_OFTA_SuratDinas_Keperluan DEFAULT(''),

	TransportID VARCHAR(3) NOT NULL CONSTRAINT DF_OFTA_SuratDinas_TransportID DEFAULT(''),
	KMAwal BIGINT NOT NULL CONSTRAINT DF_OFTA_SuratDinas_KMAwal DEFAULT(0),

	RSID VARCHAR(5) NOT NULL CONSTRAINT DF_OFTA_SuratDinas_RSID DEFAULT(''),
	
	JenisBiayaID VARCHAR(3) NOT NULL CONSTRAINT DF_OFTA_SuratDinas_JenisBiayaID DEFAULT(''),
	KasBon DECIMAL(18,0) NOT NULL CONSTRAINT DF_OFTA_SuratDinas_KasBon DEFAULT(0),

	CONSTRAINT PK_OFTA_SuratDinas_SuratDinasID PRIMARY KEY CLUSTERED(SuratDinasID)
)
