CREATE TABLE [dbo].[OFTA_Kota]
(
	KotaID VARCHAR(3) NOT NULL CONSTRAINT DF_OFTA_Kota_KotaID DEFAULT(''),
	KotaName VARCHAR(20) NOT NULL CONSTRAINT DF_OFTA_Kota_KotaName DEFAULT(''),

	CONSTRAINT PK_OFTA_Kota_KotaID PRIMARY KEY CLUSTERED(KotaID)
)
