CREATE TABLE [dbo].[OFTA_LaporanDinas]
(
	LaporanDinasID VARCHAR(14) NOT NULL CONSTRAINT DF_OFTA_LaporanDinas_LaporanDinasID DEFAULT(''),
	TglJamCreate DATETIME NOT NULL  CONSTRAINT DF_OFTA_LaporanDinas_TglJamCreate DEFAULT('1900-01-01T00:00:00'),

	ReportedPegID VARCHAR(4) NOT NULL CONSTRAINT DF_OFTA_LaporanDinas_ReportedPegID DEFAULT(''),
	SuratDinasID VARCHAR(14) NOT NULL CONSTRAINT DF_OFTA_LaporanDinas_SuratDinasID DEFAULT(''),

	TglSelesai DATETIME NOT NULL CONSTRAINT DF_OFTA_LaporanDinas_TglSelesai DEFAULT('1900-01-01T00:00:00'),
	HasilKerja VARCHAR(MAX) NOT NULL CONSTRAINT DF_OFTA_LaporanDinas_HailKerja DEFAULT(''),
	KMAkhir BIGINT NOT NULL CONSTRAINT DF_OFTA_LaporanDinas_KMAkhir DEFAULT(0),

	CONSTRAINT PK_LaporanDinas_LaporanDinasID PRIMARY KEY CLUSTERED(LaporanDinasID)
)

