CREATE TABLE [dbo].[OFTA_RS]
(
	RSID VARCHAR(5) NOT NULL CONSTRAINT DF_OFTA_RS_RSID DEFAULT(''),
	RSName VARCHAR(30) NOT NULL CONSTRAINT DF_OFTA_RS_RSName DEFAULT(''),
	KotaID VARCHAR(3) NOT NULL CONSTRAINT DF_OFTA_RS_KotaID DEFAULT(''),

	CONSTRAINT PK_OFTA_RS_RSID PRIMARY KEY CLUSTERED(RSID)
)
