CREATE TABLE [dbo].[OFTA_Peg]
(
	PegID VARCHAR(5) NOT NULL CONSTRAINT DF_OFTA_Peg_PegID DEFAULT(''),
	PegName VARCHAR(30) NOT NULL CONSTRAINT DF_OFTA_Peg_PegName DEFAULT(''),
	JabatanID VARCHAR(3) NOT NULL CONSTRAINT DF_OFTA_Peg_JabatanID DEFAULT(''),

	CONSTRAINT PK_OFTA_Peg_PegID PRIMARY KEY CLUSTERED (PegID)
)
