CREATE TABLE [dbo].[OFTA_ParamNo]
(
	ParamID VARCHAR(10) NOT NULL CONSTRAINT OFTA_ParamNo_ParamID DEFAULT(''),
	ParamValue VARCHAR(10) NOT NULL CONSTRAINT OFTA_ParamNo_ParamValue DEFAULT(''),

	CONSTRAINT PK_OFTA_ParamNo_ParamID PRIMARY KEY CLUSTERED(ParamID)
)
